"""
scout_types.py — TypedDict contracts for Scout data shapes.

These are type hints only — no runtime enforcement. They exist to surface
field drift at the type-checker level and document the expected shape of
the dicts that flow between modules.

Import with:
    from scout_types import Offer, Brief, FormattedOffer, PulseSignal

Usage:
    mypy scout_types.py offer_scraper.py scout_agent.py --ignore-missing-imports
"""

from typing import Optional, TypedDict


# ── Offer ──────────────────────────────────────────────────────────────────────
# Shape produced by offer_scraper.py and stored in offers_latest.json.
# Maps 1:1 to OFFER_FIELDS in offer_scraper.py.

class Offer(TypedDict, total=False):
    # Identity
    network: str
    offer_id: str
    advertiser: str

    # Creative & copy
    title: str
    description: str
    cta: str
    terms: str
    mini_description: str

    # Payout
    payout: str
    payout_type: str
    currency: str

    # Targeting & geo
    geo: str
    geo_raw: str            # raw geo string before normalization
    os_targeting: str       # "All" on most networks — low signal
    platform_targeting: str # "All" on most networks — low signal

    # Categorization
    category: str

    # Creatives — URLs for MS platform upload
    icon_url: str
    hero_url: str
    banner_url: str

    # Tracking
    tracking_url: str
    preview_url: str

    # Status & metadata
    status: str
    date_scraped: str

    # Internal enrichment — added by scout_agent.py, not the scraper
    _ms_status: str
    _ms_internal_name: str
    _payout_num: Optional[float]
    _payout_type_norm: str
    _raw_payout: str
    _scout_score: Optional[float]


# ── FormattedOffer ─────────────────────────────────────────────────────────────
# Shape returned by _format_offers() in scout_agent.py.
# This is the most-shared intermediate dict in the agent pipeline —
# consumed by _build_opportunity_cards (scout_bot.py), get_offers_for_publisher,
# ask(), and scout_digest.py.
#
# Key fields added in PRs #18 and #19:
#   offer_id   — required for selective button replacement in _handle_approve
#   risk_flag  — non-empty string suppresses "Add to Queue" button

class FormattedOffer(TypedDict, total=False):
    advertiser: str
    network: str
    offer_id: str           # required for selective button replacement (PR #18)
    payout: str
    payout_num: Optional[float]
    payout_type: str
    category: str
    geo: str
    ms_status: str
    ms_internal_name: str
    scout_score_rpm: Optional[float]
    performance_context: str
    risk_flag: str          # empty string if no risk; non-empty suppresses Add to Queue (PR #19)
    # Fields present when offer includes creative data
    icon_url: str
    hero_url: str
    tracking_url: str


# ── Brief ──────────────────────────────────────────────────────────────────────
# Shape produced by draft_campaign_brief() in scout_agent.py and stored
# in data/pending_briefs.json. Used to populate the Notion queue page
# and the Slack brief card.

class Brief(TypedDict, total=False):
    advertiser: str
    description: str
    payout: str
    payout_type: str
    geo: str
    category: str
    hero_url: str
    icon_url: str
    banner_url: str
    tracking_url: str
    network: str
    offer_id: str
    # Platform copy fields (generated by AI or pre-filled from offer)
    platform_title: Optional[str]
    platform_cta_yes: Optional[str]
    platform_cta_no: Optional[str]
    # AI-generated copy block — populated by _generate_offer_copy()
    ai_copy: Optional[dict]  # keys: headline, short_headline, description, short_desc, cta_yes, cta_no, goal_title
    # Intelligence context from Scout
    estimated_rpm: Optional[float]
    perf_ctx: str
    risk_flag: str


# ── PulseSignal ────────────────────────────────────────────────────────────────
# Shape produced by _run_pulse_signals() in scout_bot.py.
# Each signal type is one entry in the list returned by _run_pulse_signals.

class PulseSignal(TypedDict, total=False):
    signal_type: str     # "ghost" | "cap" | "velocity" | "fill" | "overnight" | "opportunity"
    title: str
    body: str
    urgency: str         # "high" | "medium" | "low"
    data: list           # list[dict] — raw signal rows, shape varies by signal_type
